- name: Install required packages
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes
  become: true

- name: Download AWS CLI v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'

- name: Unzip AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

#- name: Install AWS CLI
#  command: /tmp/aws/install
#  become: true

- name: install kubectl
  become: true
  shell: |
    curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.4/2024-09-11/bin/linux/amd64/kubectl
    curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.30.4/2024-09-11/bin/linux/amd64/kubectl.sha256
    sha256sum -c kubectl.sha256
    openssl sha1 -sha256 kubectl
    chmod +x ./kubectl
    mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
    echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc
    sudo mv $HOME/bin/kubectl /usr/local/bin/kubectl
    sudo chmod +x /usr/local/bin/kubectl
    kubectl version --client