---
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
  tag:Name:
    - jenkins_server
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'/home/ashgan/.ssh/ec2_key.pem'"

